### ISSUE TITLE
Showing Null Error

### ISSUE THREAD

**Issue by AdelSadiq** [World-Package/validation_textformfield#1]
When trying to to give input text, error occurs. The error is that "Null check operator used on a null value". Whats the problem ?

**Comment by Tbsdev-Anmol** [comment]
Hello @AdelSadiq 

I apologize for the error. 

Can you share the code that you did so, that I can check and help you to resolve the issue.?

Thank you.

**Comment by AdelSadiq** [comment]
`
class SignUp extends StatefulWidget {
  const SignUp({Key? key}) : super(key: key);

  @override
  State<SignUp> createState() => _SignUpState();
}

class _SignUpState extends State<SignUp> {
  final TextEditingController nameController = TextEditingController();


 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          height: Get.height,
          width: Get.width,
          color: PABColorTheme.backgrndColor,
          padding: const EdgeInsets.symmetric(horizontal: 24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 124),
              Text(
                "Okay, Lets get\nstarted",
                style: PABTextTheme.headline1
                    .copyWith(color: Colors.white, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 6),
              Text(
                "Join us, and get your dream job",
                style: PABTextTheme.headline2.copyWith(color: Colors.white54),
              ),
              const SizedBox(height: 32),
              EmailValidationTextField(
                whenTextFieldEmpty: "Please enter  email",
                validatorMassage: "Please enter valid email",
                keyboardType: TextInputType.text,
                style: const TextStyle(color: Colors.white),
                decoration: InputDecoration(
                    focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: const BorderSide(color: Colors.white)),
                    enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: const BorderSide(color: Colors.white)),
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: const BorderSide(color: Colors.white)),
                    counterText: '',
                    labelStyle: PABTextTheme.content.copyWith(
                        color: const Color.fromRGBO(255, 255, 255, 1)),
                    hintText: "Email Address",
                    hintStyle:
                        PABTextTheme.content.copyWith(color: Colors.white38)),
                textEditingController: nameController ,
              ),
              const Spacer(),
              Container(
                padding: const EdgeInsets.only(bottom: 32),
                width: Get.width,
                child: TextButton(
                    child: Text(
                      'Register Now',
                      style: PABTextTheme.content.copyWith(color: Colors.white),
                    ),
                    style: TextButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                          vertical: 15, horizontal: 31),
                      primary: Colors.white,
                      backgroundColor: PABColorTheme.primaryColor,
                      shape: const RoundedRectangleBorder(
                        borderRadius: BorderRadius.all(Radius.circular(31)),
                      ),
                    ),
                    onPressed: () async {
                      );
                    }),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by AdelSadiq** [comment]
`class SignUp extends StatefulWidget {
  const SignUp({Key? key}) : super(key: key);

  @override
  State<SignUp> createState() => _SignUpState();
}

class _SignUpState extends State<SignUp> {
  final TextEditingController emailController = TextEditingController();
 

 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          height: Get.height,
          width: Get.width,
          color: PABColorTheme.backgrndColor,
          padding: const EdgeInsets.symmetric(horizontal: 24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 124),
              Text(
                "Okay, Lets get\nstarted",
                style: PABTextTheme.headline1
                    .copyWith(color: Colors.white, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 6),
              Text(
                "Join us, and get your dream job",
                style: PABTextTheme.headline2.copyWith(color: Colors.white54),
              ),
              const SizedBox(height: 32),
              EmailValidationTextField(
                whenTextFieldEmpty: "Please enter  email",
                validatorMassage: "Please enter valid email",
                keyboardType: TextInputType.text,
                style: const TextStyle(color: Colors.white),
                decoration: InputDecoration(
                    focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: const BorderSide(color: Colors.white)),
                    enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: const BorderSide(color: Colors.white)),
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                        borderSide: const BorderSide(color: Colors.white)),
                    counterText: '',
                    labelStyle: PABTextTheme.content.copyWith(
                        color: const Color.fromRGBO(255, 255, 255, 1)),
                    hintText: "Email Address",
                    hintStyle:
                        PABTextTheme.content.copyWith(color: Colors.white38)),
                textEditingController: emailController,
              ),
              const Spacer(),
              Container(
                padding: const EdgeInsets.only(bottom: 32),
                width: Get.width,
                child: TextButton(
                    child: Text(
                      'Register Now',
                      style: PABTextTheme.content.copyWith(color: Colors.white),
                    ),
                    style: TextButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                          vertical: 15, horizontal: 31),
                      primary: Colors.white,
                      backgroundColor: PABColorTheme.primaryColor,
                      shape: const RoundedRectangleBorder(
                        borderRadius: BorderRadius.all(Radius.circular(31)),
                      ),
                    ),
                    onPressed: () async {}),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by Tbsdev-Anmol** [comment]
Hello @AdelSadiq

Can you share the flutter version because the flutter version issues a null safety error
This package test on flutter (**Channel stable, 3.0.0**) 
**environment:
  sdk: ">=2.13.0-68.0.dev <3.0.0"**


It's working fine 


**Either**


Use `onChanged: (val){},`


**Full Code** 



```

 EmailValidationTextField(
onChanged: (val){},
         validatorMassage: "Please enter valid email",
            keyboardType: TextInputType.text,
            style: const TextStyle(color: Colors.black),
            decoration: InputDecoration(
                focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: const BorderSide(color: Colors.black)),
                enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: const BorderSide(color: Colors.black)),
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: const BorderSide(color: Colors.black)),
                counterText: '',

                hintText: "Email Address",

            ),
            textEditingController: emailController,

          )

```




Thank you.😊

**Comment by AdelSadiq** [comment]
Use of `onChanged: (val){},` solve the error. 
Thank You
