### ISSUE TITLE
Showing more padding 

### ISSUE THREAD

**Issue by AdelSadiq** [World-Package/validation_textformfield#2]
Hi,

Showing more padding in between password textfield & confirm password textfield even i didnt give one.

![Screenshot 2022-05-12 181706](https://user-images.githubusercontent.com/88178816/168078088-7b8e7fe5-073a-42f9-8eca-1d0b3041f479.png)

**Comment by Tbsdev-Anmol** [comment]
Hello @AdelSadiq 
I apologize for the error
**Use New Version (2.2.5)** 

Thank you.😊
